### ISSUE TITLE
Occasional white noise with XMI looping

### ISSUE THREAD

**Issue by afritz1** [Mindwerks/wildmidi#148] opened 2016-07-27 17:33 UTC
Hi, I'm developing an open-source remake of The Elder Scrolls I: Arena ([link](https://github.com/afritz1/OpenTESArena)). @psi29a directed me here from [this comment](https://github.com/afritz1/OpenTESArena/issues/38#issuecomment-235366808) regarding a split second of white noise I occasionally hear when some XMI songs loop.

I ran `wildmidi.exe` version 0.4.0 with `VISION.XMI` (Dropbox [link](https://www.dropbox.com/s/thv5bmln4s2gwnv/xmi_files.tar.gz?dl=0)) in cmd.exe on Windows 7. I used the eawpats library and Timidity/Gravis config for `wildmidi.cfg`. I haven't been able to reproduce the white noise there because I don't see a way to make the song loop on the command line. However, when playing `VISION.XMI` in OpenTESArena during the cinematic with Ria Silmane, it _always_ has a split second of white noise upon looping the first time, maybe 150ms to 250ms long, and it happens maybe every third or fourth loop after, so it's reproducible there.

As a side note, `wildmidi.exe` also crashes when `VISION.XMI` (or any XMI, really) finishes, with the "wildmidi.exe has stopped working" message. There are no problems with WildMIDI crashing in OpenTESArena, though.

**Comment by chrisisonwildcode** [comment] 2016-07-27 23:03
Hi Aaron,

Can you please explain how you are doing the looping (so we can reproduce accurately). This will help to resolve the issue reported much faster.

Chris

**Comment by afritz1** [comment] 2016-07-28 00:37
The WildMIDI code and OpenAL Soft code in my project was written by @kcat. I'm afraid I don't know as much about MIDI code as I should (I just switched from FMOD a few weeks ago), but I can try pointing out a few places that seem relevant, though:

[AudioManager.cpp#L301](https://github.com/afritz1/OpenTESArena/blob/885a378cc4fed5fd1599809d5404472086e5aca8/OpenTESArena/src/Media/AudioManager.cpp#L301)
[WildMidi.cpp#L51](https://github.com/afritz1/OpenTESArena/blob/885a378cc4fed5fd1599809d5404472086e5aca8/OpenTESArena/src/Media/WildMidi.cpp#L51)
[WildMidi.cpp#L62](https://github.com/afritz1/OpenTESArena/blob/885a378cc4fed5fd1599809d5404472086e5aca8/OpenTESArena/src/Media/WildMidi.cpp#L62)

I hope this helps. kcat would be able to explain it better. Thanks for your time.

**Comment by chrisisonwildcode** [comment] 2016-07-28 07:18
@kcat My CPP knowledge is limited however have some basic understanding of it.

Looking at the read in your AudioManager.cpp below Line 301. Is it the way I'm reading it or is it reading past the end of the data?

**Comment by kcat** [comment] 2016-07-28 12:25
@chrisisonwildcode It's not reading past the end of the data. Although I do see the problem now. It's your typical bytes vs samples mixup. It's offsetting the buffer pointer for the looped read according to how many sample frames it got, even though it's a byte pointer, so it's not being incremented enough and is being written to incorrectly. Sorry the for noise (pun not intended), it's not a problem with WildMIDI.

**Comment by afritz1** [comment] 2016-07-28 15:54
The white noise is fixed! Thanks, @kcat. It was a problem with our code, not WildMIDI's.

**Comment by sezero** [comment] 2016-07-28 16:53
Closing.

**Closed by sezero** 2016-07-28 16:53 UTC

**Comment by psi29a** [comment] 2016-07-28 17:56
\o/  thanks @kcat and @chrisisonwildcode 

Another satisfied customer! ;)

**Comment by afritz1** [comment] 2016-07-28 18:23
_Almost_ satisfied. Just need the XMI looping now, and _then_ WildMIDI will get my star :)

**Comment by psi29a** [comment] 2016-07-28 18:30
hah! challenge accepted!
