### ISSUE TITLE
0.3.8 - Releases going on forever!

### ISSUE THREAD

**Issue by Hellser** [Mindwerks/wildmidi#132] opened 2015-12-30 10:08 UTC
Hi there. I'm a Windows user (and hopefully, this applies to the development of the 0.4 release); I also use the official Gravis Ultrasound PATs. A source port for Doom I use (ZDoom) recently added WildMidi support in hopes to let go of Timidity++ - as Timidity often didn't loop songs seamlessly where as WildMidi does. Now, back to the issue:

According to what we noticed (by we, I mean the people using ZDoom) - some of the instruments don't "Release" properly - one note continues on for a long time. This even occurs with the wildmidi execute provided by this here github.

I've heard about the "guspat_editor_author_cant_read_so_fix_release_time_for_me" token to add to the config, but this didn't do anything at all. Is there a way to fix this issue, or is it a flaw that can't be fixed?

**Comment by chrisisonwildcode** [comment] 2016-04-18 03:58
If you could link the offending gust file plus music file then I can get a better look at it.

**Comment by psi29a** [comment] 2016-07-20 06:30
@Hellser Have you tried WildMIDI 0.4?  Does looping work seamlessly as before? How about note release?

**Comment by sezero** [comment] 2017-03-17 12:56
We have yet to hear from the bug reporter about this with 0.4.1.

**Comment by Hellser** [comment] 2017-06-06 04:14
Sorry about the very long delay. 0.4.1 has the same exact problem. I am including in the attachment the following: E1M6 from Doom, the song as played by Wildmidi and one from Timidity++. As well as the offending .pat file. The problem is, it's not JUST this .pat file that is having the issue. I've heard this problem with other instruments that I cannot tell what they are exactly.

Also included is another example. Once again, one version by wildmidi and another by Timidity++.
Once again as mentioned earlier, I am using the official Gravis Ultrasound PATs.

[funkystars.zip](https://github.com/Mindwerks/wildmidi/files/1053804/funkystars.zip)
[Wildmidi.zip](https://github.com/Mindwerks/wildmidi/files/1053790/Wildmidi.zip)

**Comment by chrisisonwildcode** [comment] 2017-06-07 00:37
This should not be happening so I will look into it by the weekend. Thanks for the attachments Bret it will help find the cause.

I apologise for not being active, a whole lot was going on in my personal life but it has been settling down and I will be getting back into going through the bugs.

Chris

**Comment by chrisisonwildcode** [comment] 2017-06-13 09:58
Hellser, thanks for getting back to us. I'm still working out if this is a bug, bad config, or bad timidity behaviour.

Substituting the pats provided into my patch set I found both pats had the "made by a bad editor" bug, which wildmidi adjusted for as you would expect. I did note though that with funky stars.mid it is likely the instrument in config setting 100 that is causing the issues and not the squrwave.pat you provided, and the slowstr.pat you provided has an almost 2s normal release time so the sound is blending together a little.

I am going to go back to the specs and original Gravis pats and compare what we're doing. This will hopefully help come up with a reasonable solution. Please be patient as I slowly get back into researching and fixing this stuff. The reason I will do it this way is that there has been so many "fixes" due to pats doing weird things it is making me think we are doing something wrong, or compensating too much for problems that need to be resolved elsewhere.

**Comment by Hellser** [comment] 2017-06-17 19:11
Alright. Thanks for looking into this.

**Comment by chrisisonwildcode** [comment] 2017-06-27 10:24
FYI, Just updated master, please try and comment.

**Comment by sezero** [comment] 2017-06-29 05:40
@Hellser:  @chrisisonwildcode pushed commit d40186f21 for this. Please try and comment.

**Comment by Hellser** [comment] 2017-06-30 16:03
I don't have a compiling environment to test this, I'm afraid.

**Comment by sezero** [comment] 2017-07-01 01:17
[win32.zip](https://github.com/Mindwerks/wildmidi/files/1116768/win32.zip)
[win64.zip](https://github.com/Mindwerks/wildmidi/files/1116769/win64.zip)

Here are win32 and win64 dll builds. Download 0.4.1 release, and then replace the relevant dll from these builds.

**Comment by psi29a** [comment] 2017-07-01 07:35
Thank you @sezero for doing this. :)

**Comment by Hellser** [comment] 2017-07-06 13:41
This seems to of have fixed it. Sounds a lot better than before. Thank you!

**Comment by psi29a** [comment] 2017-07-06 17:44
Interesting. :)  So it was the fixes for bad/screwed up patches that was causing problems in other areas. What a mess (on patch sets and midi side).

**Comment by sezero** [comment] 2017-07-07 07:01
OK then.  @chrisisonwildcode: Do you intend to make a backport of the fix to wildmidi-0.3 branch?

**Comment by psi29a** [comment] 2017-07-11 13:53
I consider this bug closed when back-ported to 0.3 branch.

@sezero how long are we going to keep supporting 0.3 branch?

**Comment by sezero** [comment] 2017-07-11 13:58
On 7/11/17, Bret Curtis <notifications@github.com> wrote:
> I consider this bug closed when back-ported to 0.3 branch.

If @chrisisonwildcode won't make a backport, just close it.

> @sezero how long are we going to keep supporting 0.3 branch?

Don't know, I'm getting bored with it already.

**Comment by psi29a** [comment] 2017-07-11 18:29
Do you know who is still using it?

**Comment by sezero** [comment] 2017-07-11 18:54
> Do you know who is still using it?

Gentoo still has 0.3.8 (possibly they haven't bothered updating)

Cygwin seems to have recently packcged 0.3.12:
http://cygwin.1069669.n5.nabble.com/wildmidi-0-3-12-1-td134878.html

Other than those, I don't know.

**Comment by sezero** [comment] 2017-07-18 11:07
Closing this (no replies from @chrisisonwildcode wrt backporting.)

**Closed by sezero** 2017-07-18 11:07 UTC
Labels: bug
