### ISSUE TITLE
AmigaOS4: 0.3.14 completly oversteers volume

### ISSUE THREAD

**Issue by raziel-** [Mindwerks/wildmidi#203] opened 2018-10-08 19:31 UTC
Hi wildmidi-team,

I ported wildmidi to AmigaOS4 the other day (though i haven't had the time to upload it to the Depot yet), then i saw that a new version was rolled out and wanted to update my build, but alas, while 0.3.13 works fine, 0.3.14 introduces a nasty oversteering of the volume.

It's so bad that EVERY volume over 3 (yes, 3!!!) will produce massive noise.
Even with the volume set to 3 some songs noise out when the drums set in.
Setting the volume to 2 works better, but then songs start to eat away notes.

As i said, using the 0.3.13 build is perfectly fine, so i wonder what changed AmigaOS4/AHI-wise...

Thanks a bunch for any pointers

**Comment by sezero** [comment] 2018-10-08 19:44
Actually nothing ever changed AHI-wise between 0.3.13 and 0.3.14.

Can you pinpoint the offending commit in the wildmidi-0.3 branch? That
would be a big help.

**Comment by raziel-** [comment] 2018-10-08 19:48
My luck :-/

I can only bisect manually, that will take time, but i'll try

**Comment by sezero** [comment] 2018-10-08 19:55
> I can only bisect manually, that will take time, but i'll try

That would be a big help, because I don't see where the problem would be.
Thanks in advance!

**Comment by sezero** [comment] 2018-10-08 19:57
@psi29a: Do you have any problems with 0.3.14 release on any of your setups?

**Comment by raziel-** [comment] 2018-10-08 19:58
Actually, i just realized that i got the 0.4.2 source from ... somewhere.

The only thing different in the AHI code is this line which uses int8_t instead of char
static int8_t *AHIBuf[2] = { NULL, NULL };

Need to see if that makes a difference

**Comment by sezero** [comment] 2018-10-08 20:03
0.4 series is quite different than 0.3 series.  To clarify things: is 0.3.14 really
causing problems?

**Comment by raziel-** [comment] 2018-10-08 20:12
I'm afraid so

0.3.13 and 0.3.14 are unusable on AmigaOS4 due to the noise they produce with higher volumes.

**Comment by sezero** [comment] 2018-10-08 20:18
You had said "0.3.13 build is perfectly fine": 0.3.13 is bad too??

**Comment by raziel-** [comment] 2018-10-08 20:19
Yes, sorry, i mixed 0.3.13 with the 0.4.2 source i had built (0.4.2 is fine though)

**Comment by raziel-** [comment] 2018-10-08 20:23
I was mixing the two releases because they have exactly the same changelog, apologies

**Comment by raziel-** [comment] 2018-10-08 20:25
Guess, i'll wait for the 0.4.3 then, sorry for the noise

**Comment by sezero** [comment] 2018-10-08 20:26
In that case, can you try the 0.3.12 release: is it good? If it is really good,
can you then try reverting the following commit in 0.3.14 and try it again:
https://github.com/Mindwerks/wildmidi/commit/7333ce73a8935b103d412a2893a36ac3ad7cd184
That commit is the only AHI-wise significant difference between 0.3.12 and
0.3.14, and that change is not in 0.4.2 but it is in not-yet-released 0.4.3:
so I am interested in the result of this experiment.  (You can also try building
from the master branch to see how 0.4.3 works for you on os4.)

**Comment by raziel-** [comment] 2018-10-08 20:42
No, sorry, 0.3.12 is bad too

but

0.4.1 is fine :-/

**Comment by raziel-** [comment] 2018-10-08 20:44
About that commit:
Wouldn't it be easier to just change the define to both times use MEMF_PUBLIC?

I'll try to revert that commit

**Comment by sezero** [comment] 2018-10-08 20:48
> Wouldn't it be easier to just change the define to both times use MEMF_PUBLIC?

os4 deprecated MEMF_PUBLIC. They suggest using MEMF_SHARED
http://wiki.amigaos.net/wiki/Obsolete_Exec_Memory_Allocation

**Comment by raziel-** [comment] 2018-10-08 20:50
reverting the commit does not help, i'm afraid

**Comment by raziel-** [comment] 2018-10-08 20:56
Checking your idea the other way round works, though

0.4.2 with MEMF_SHARED is still working great

**Comment by sezero** [comment] 2018-10-08 20:58
>  No, sorry, 0.3.12 is bad too but 0.4.1 is fine :-/

I wonder.. One big difference between 0.3.x and 0.4.x is that
0.3.x library specifically outputs little endian pcm data, whereas
the 0.4.x library outputs host-endian pcm data.  For that reason,
wee byte-swap the pcm data before sending to AHI in 0.3.x on
big endian platforms such as aos4.  However, the case is the 
reverse for wav file generation: wav files must be little endian,
so 0.3.x does not byte swap the pcm data at all before writing to
a wav, but 0.4.x does byte-swap when writing to a wav on big
endian platforms.

Questions:

- How do you compile (0.3 or 0.4 doesn't matter)?
  You must compile by changing into the amiga directory and
  run "make amigaos4".  That should define WORDS_BIGENDIAN
  If you accidentally built without WORDS_BIGENDIAN defined, all
  kinds of issues will show up.

- Take 0.3.14, and run "wildmidi -o xx.wav some.mid", and try
 playing the generated xx.wav.  Is the generated wav good?

- Take 0.4.x, do the same as above: is the generated wav good?

**Comment by raziel-** [comment] 2018-10-08 21:06
checked out the 0.4.3 branch and it is fine, i don't understand :-/

Compiling:
Yes, changing into amiga/, and running "gmake amigaos4", beforehand i need to comment out the -noixemul lines from gcc_os4.cfg, because this breaks compiling as -noixemul seems to be an unknown option

WAV Building:
0.3.14 produces a .wav file which contains purely of noise
0.4.2 produces a perfectly fine .wav file

**Comment by sezero** [comment] 2018-10-08 21:15
> -noixemul seems to be an unknown option

Huh.. Newer gcc for os4 removed that option then.. I only tested
gcc-4.2.4 in a cross-compile environment on linux and it does have
the -noixemul option.

> WAV Building:
> 0.3.14 produces a .wav file which contains purely of noise
> 0.4.2 produces a perfectly fine .wav file

Then I am out of ideas.  All build switches and all OS-specific
audio output drivers are the same between 0.3 and 0.4; well
except for stdint.h types and native C89 types, and of course
the endian handling. Those differences are isolated in player
code (wildmidi.c): can you see anything suspicious in there
if you compare 0.3.14 and 0.4.3?

@psi29a: any ideas?

**Comment by raziel-** [comment] 2018-10-08 21:39
GCC:
Maybe it's because i'm using gcc (adtools build 8.1.0) 8.1.0 here?

Player:
Only the stdint.h types that differ (uint8_t and cast) but i doubt they are the reason for the volume fault/noise on replaying?

**Comment by sezero** [comment] 2018-10-08 21:44
> GCC:
> Maybe it's because i'm using gcc (adtools build 8.1.0) 8.1.0 here?

It may be.  Do you have access to an older gcc / toolchain by any chance?
(BTW, I am writing to an amiga fellow, maybe he has an idea.)

> Player:
> Only the stdint.h types that differ (uint8_t and cast) but i doubt they are
> the reason for the volume fault/noise on replaying?

I strongly doubt that: same thing works fine elsewhere.

**Comment by raziel-** [comment] 2018-10-08 21:57
GCC:
Of course i do
4.2.4 knows this switch
4.9.1 and onward has forgotten about it
Somewhere between those two releases they dropped the -noixemul switch

**Comment by sezero** [comment] 2018-10-08 22:01
Does 0.3.x (e.g. 0.3.14) work correctly if you build with gcc-4.2.4?

**Comment by raziel-** [comment] 2018-10-08 22:03
Sorry, missed that piece of information

Nope, it still produces only noise in a higher volume setting than 3

**Comment by sezero** [comment] 2018-10-08 22:10
OK then, I'll be waiting for Szilárd Biró (https://github.com/BSzili/) to reproduce this and comment on things.

**Comment by raziel-** [comment] 2018-10-08 22:19
Hehe, Amigaland is small, i know him from the forums :-)

**Comment by psi29a** [comment] 2018-10-09 11:31
I have nothing to test this on aside from x86/x86_64 it is for me not reproducible. 

Does this have to do with newer gcc builds on AmigaOS?

**Comment by sezero** [comment] 2018-10-09 12:42
He reported that gcc4-built versions doesn't behave for him.

**Comment by psi29a** [comment] 2018-10-09 15:06
And if WORDS_BIGENDIAN is not defined (undeffed), can you reproduce the noise?

**Comment by sezero** [comment] 2018-10-09 15:17
> And if WORDS_BIGENDIAN is not defined (undeffed), can you reproduce the noise?

Was too lazy to go back to the mac, so I did the opposite: I built it for
my i686 linux with WORDS_BIGENDIAN specifically defined: it does
produce a bad noise (and to reproduce the original description of the
issue, the actual melody can be heard amongst the noise.)

So I do _think_ that this is an issue with endianism handling, but I
don't see how: the bug reporter says (IIRC) that WORDS_BIGENDIAN
is defined in his builds.

**Comment by sezero** [comment] 2018-10-09 15:20
BTW, if you are curious and want to reproduce it on your own x86/x86_64,
take 0.3.14 release, make sure to pick openal as the output driver on your
linux and make sure to manually add WORDS_BIGENDIAN at least to the
player CFLAGS.

**Comment by sezero** [comment] 2018-10-09 15:30
> REMOVING WORDS_BIGENDIAN from the 0.3.14 build and what do you know,
> it works!!! :-)

Well now, that's interesting:  Is your amiga computer using little-endian mode?
(ppc is a 'swings-both-ways cpu after all..)

And I would like to see the built-in defines of your gcc, too, for both 4.2.4 and 8.1.
For that, on linux, I do:
`  gcc -E -dD -xc /dev/null > gccdefs.h`

**Comment by sezero** [comment] 2018-10-09 15:32
(And what's more interesting is how the hell does the 0.4.x work properly with WORDS_BIGENDIAN defined?..)

**Comment by raziel-** [comment] 2018-10-09 15:43
Yes, one of the many mysteries i tend to see on this platform :-)

"Normally" everything is or should be made available in BigEndian

Can i provide you with the gccdefs.h in some other way?
That line doesn't work for me

gcc -E -dD -xc > ram:gccdefs.h
gcc: warning: '-x c' after last input file has no effect
gcc: fatal error: no input files
compilation terminated.

**Comment by raziel-** [comment] 2018-10-09 15:44
Sorry, here it the correct one

gcc -E -dD -xc /dev/null > gccdefs.h
gcc: error: /dev/null: No such file or directory
gcc: warning: '-x c' after last input file has no effect
gcc: fatal error: no input files
compilation terminated.

**Comment by sezero** [comment] 2018-10-09 15:48
You should replace /dev/null with the 'nul' device name specific to amigaos.

Anyways, easier method would be creating an empty C file, like 0.c and running:
`gcc -E -dD -xc 0.c > gccdefs.h`

**Comment by sezero** [comment] 2018-10-09 15:54
And I am curious:

- With WORDS_BIGENDIAN definition removed, 0.3.14 outputs correctly to AHI.
  Does it generate a correct wav file?

- If you remove WORDS_BIGENDIAN definition from 0.4.x, does it work correctly?
  (both output to AHI and wav file generation.)

**Comment by raziel-** [comment] 2018-10-09 18:38
gccdefs.h

# 1 "0.c"
# 1 "<built-in>"
#define __STDC__ 1
#define __STDC_VERSION__ 201710L
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_HOSTED__ 1
#define __GNUC__ 8
#define __GNUC_MINOR__ 1
#define __GNUC_PATCHLEVEL__ 0
#define __VERSION__ "8.1.0"
#define __ATOMIC_RELAXED 0
#define __ATOMIC_SEQ_CST 5
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_RELEASE 3
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __FINITE_MATH_ONLY__ 0
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG__ 4
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_LONG_DOUBLE__ 8
#define __SIZEOF_SIZE_T__ 4
#define __CHAR_BIT__ 8
#define __BIGGEST_ALIGNMENT__ 16
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_PDP_ENDIAN__ 3412
#define __BYTE_ORDER__ __ORDER_BIG_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_BIG_ENDIAN__
#define __SIZEOF_POINTER__ 4
#define __SIZE_TYPE__ unsigned int
#define __PTRDIFF_TYPE__ int
#define __WCHAR_TYPE__ long int
#define __WINT_TYPE__ unsigned int
#define __INTMAX_TYPE__ long long int
#define __UINTMAX_TYPE__ long long unsigned int
#define __CHAR16_TYPE__ short unsigned int
#define __CHAR32_TYPE__ unsigned int
#define __SIG_ATOMIC_TYPE__ int
#define __INT8_TYPE__ signed char
#define __INT16_TYPE__ short int
#define __INT32_TYPE__ int
#define __INT64_TYPE__ long long int
#define __UINT8_TYPE__ unsigned char
#define __UINT16_TYPE__ short unsigned int
#define __UINT32_TYPE__ unsigned int
#define __UINT64_TYPE__ long long unsigned int
#define __INT_LEAST8_TYPE__ signed char
#define __INT_LEAST16_TYPE__ short int
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST64_TYPE__ long long int
#define __UINT_LEAST8_TYPE__ unsigned char
#define __UINT_LEAST16_TYPE__ short unsigned int
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __INT_FAST8_TYPE__ int
#define __INT_FAST16_TYPE__ int
#define __INT_FAST32_TYPE__ int
#define __INT_FAST64_TYPE__ long long int
#define __UINT_FAST8_TYPE__ unsigned int
#define __UINT_FAST16_TYPE__ unsigned int
#define __UINT_FAST32_TYPE__ unsigned int
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __INTPTR_TYPE__ int
#define __UINTPTR_TYPE__ unsigned int
#define __has_include(STR) __has_include__(STR)
#define __has_include_next(STR) __has_include_next__(STR)
#define __GXX_ABI_VERSION 1012
#define __USING_SJLJ_EXCEPTIONS__ 1
#define __SCHAR_MAX__ 0x7f
#define __SHRT_MAX__ 0x7fff
#define __INT_MAX__ 0x7fffffff
#define __LONG_MAX__ 0x7fffffffL
#define __LONG_LONG_MAX__ 0x7fffffffffffffffLL
#define __WCHAR_MAX__ 0x7fffffffL
#define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)
#define __WINT_MAX__ 0xffffffffU
#define __WINT_MIN__ 0U
#define __PTRDIFF_MAX__ 0x7fffffff
#define __SIZE_MAX__ 0xffffffffU
#define __SCHAR_WIDTH__ 8
#define __SHRT_WIDTH__ 16
#define __INT_WIDTH__ 32
#define __LONG_WIDTH__ 32
#define __LONG_LONG_WIDTH__ 64
#define __WCHAR_WIDTH__ 32
#define __WINT_WIDTH__ 32
#define __PTRDIFF_WIDTH__ 32
#define __SIZE_WIDTH__ 32
#define __INTMAX_MAX__ 0x7fffffffffffffffLL
#define __INTMAX_C(c) c ## LL
#define __UINTMAX_MAX__ 0xffffffffffffffffULL
#define __UINTMAX_C(c) c ## ULL
#define __INTMAX_WIDTH__ 64
#define __SIG_ATOMIC_MAX__ 0x7fffffff
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __SIG_ATOMIC_WIDTH__ 32
#define __INT8_MAX__ 0x7f
#define __INT16_MAX__ 0x7fff
#define __INT32_MAX__ 0x7fffffff
#define __INT64_MAX__ 0x7fffffffffffffffLL
#define __UINT8_MAX__ 0xff
#define __UINT16_MAX__ 0xffff
#define __UINT32_MAX__ 0xffffffffU
#define __UINT64_MAX__ 0xffffffffffffffffULL
#define __INT_LEAST8_MAX__ 0x7f
#define __INT8_C(c) c
#define __INT_LEAST8_WIDTH__ 8
#define __INT_LEAST16_MAX__ 0x7fff
#define __INT16_C(c) c
#define __INT_LEAST16_WIDTH__ 16
#define __INT_LEAST32_MAX__ 0x7fffffff
#define __INT32_C(c) c
#define __INT_LEAST32_WIDTH__ 32
#define __INT_LEAST64_MAX__ 0x7fffffffffffffffLL
#define __INT64_C(c) c ## LL
#define __INT_LEAST64_WIDTH__ 64
#define __UINT_LEAST8_MAX__ 0xff
#define __UINT8_C(c) c
#define __UINT_LEAST16_MAX__ 0xffff
#define __UINT16_C(c) c
#define __UINT_LEAST32_MAX__ 0xffffffffU
#define __UINT32_C(c) c ## U
#define __UINT_LEAST64_MAX__ 0xffffffffffffffffULL
#define __UINT64_C(c) c ## ULL
#define __INT_FAST8_MAX__ 0x7fffffff
#define __INT_FAST8_WIDTH__ 32
#define __INT_FAST16_MAX__ 0x7fffffff
#define __INT_FAST16_WIDTH__ 32
#define __INT_FAST32_MAX__ 0x7fffffff
#define __INT_FAST32_WIDTH__ 32
#define __INT_FAST64_MAX__ 0x7fffffffffffffffLL
#define __INT_FAST64_WIDTH__ 64
#define __UINT_FAST8_MAX__ 0xffffffffU
#define __UINT_FAST16_MAX__ 0xffffffffU
#define __UINT_FAST32_MAX__ 0xffffffffU
#define __UINT_FAST64_MAX__ 0xffffffffffffffffULL
#define __INTPTR_MAX__ 0x7fffffff
#define __INTPTR_WIDTH__ 32
#define __UINTPTR_MAX__ 0xffffffffU
#define __GCC_IEC_559 2
#define __GCC_IEC_559_COMPLEX 2
#define __FLT_EVAL_METHOD__ 0
#define __FLT_EVAL_METHOD_TS_18661_3__ 0
#define __DEC_EVAL_METHOD__ 2
#define __FLT_RADIX__ 2
#define __FLT_MANT_DIG__ 24
#define __FLT_DIG__ 6
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX_10_EXP__ 38
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMAF 1
#define __DBL_MANT_DIG__ 53
#define __DBL_DIG__ 15
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX_10_EXP__ 308
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_MAX__ ((double)1.7976931348623157e+308L)
#define __DBL_MIN__ ((double)2.2250738585072014e-308L)
#define __DBL_EPSILON__ ((double)2.2204460492503131e-16L)
#define __DBL_DENORM_MIN__ ((double)4.9406564584124654e-324L)
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMA 1
#define __LDBL_MANT_DIG__ 53
#define __LDBL_DIG__ 15
#define __LDBL_MIN_EXP__ (-1021)
#define __LDBL_MIN_10_EXP__ (-307)
#define __LDBL_MAX_EXP__ 1024
#define __LDBL_MAX_10_EXP__ 308
#define __DECIMAL_DIG__ 17
#define __LDBL_DECIMAL_DIG__ 17
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMAL 1
#define __FLT32_MANT_DIG__ 24
#define __FLT32_DIG__ 6
#define __FLT32_MIN_EXP__ (-125)
#define __FLT32_MIN_10_EXP__ (-37)
#define __FLT32_MAX_EXP__ 128
#define __FLT32_MAX_10_EXP__ 38
#define __FLT32_DECIMAL_DIG__ 9
#define __FLT32_MAX__ 3.4028234663852886e+38F32
#define __FLT32_MIN__ 1.1754943508222875e-38F32
#define __FLT32_EPSILON__ 1.1920928955078125e-7F32
#define __FLT32_DENORM_MIN__ 1.4012984643248171e-45F32
#define __FLT32_HAS_DENORM__ 1
#define __FLT32_HAS_INFINITY__ 1
#define __FLT32_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMAF32 1
#define __FLT64_MANT_DIG__ 53
#define __FLT64_DIG__ 15
#define __FLT64_MIN_EXP__ (-1021)
#define __FLT64_MIN_10_EXP__ (-307)
#define __FLT64_MAX_EXP__ 1024
#define __FLT64_MAX_10_EXP__ 308
#define __FLT64_DECIMAL_DIG__ 17
#define __FLT64_MAX__ 1.7976931348623157e+308F64
#define __FLT64_MIN__ 2.2250738585072014e-308F64
#define __FLT64_EPSILON__ 2.2204460492503131e-16F64
#define __FLT64_DENORM_MIN__ 4.9406564584124654e-324F64
#define __FLT64_HAS_DENORM__ 1
#define __FLT64_HAS_INFINITY__ 1
#define __FLT64_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMAF64 1
#define __FLT32X_MANT_DIG__ 53
#define __FLT32X_DIG__ 15
#define __FLT32X_MIN_EXP__ (-1021)
#define __FLT32X_MIN_10_EXP__ (-307)
#define __FLT32X_MAX_EXP__ 1024
#define __FLT32X_MAX_10_EXP__ 308
#define __FLT32X_DECIMAL_DIG__ 17
#define __FLT32X_MAX__ 1.7976931348623157e+308F32x
#define __FLT32X_MIN__ 2.2250738585072014e-308F32x
#define __FLT32X_EPSILON__ 2.2204460492503131e-16F32x
#define __FLT32X_DENORM_MIN__ 4.9406564584124654e-324F32x
#define __FLT32X_HAS_DENORM__ 1
#define __FLT32X_HAS_INFINITY__ 1
#define __FLT32X_HAS_QUIET_NAN__ 1
#define __FP_FAST_FMAF32x 1
#define __DEC32_MANT_DIG__ 7
#define __DEC32_MIN_EXP__ (-94)
#define __DEC32_MAX_EXP__ 97
#define __DEC32_MIN__ 1E-95DF
#define __DEC32_MAX__ 9.999999E96DF
#define __DEC32_EPSILON__ 1E-6DF
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __DEC64_MANT_DIG__ 16
#define __DEC64_MIN_EXP__ (-382)
#define __DEC64_MAX_EXP__ 385
#define __DEC64_MIN__ 1E-383DD
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __DEC64_EPSILON__ 1E-15DD
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __DEC128_MIN_EXP__ (-6142)
#define __DEC128_MAX_EXP__ 6145
#define __DEC128_MIN__ 1E-6143DL
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __DEC128_EPSILON__ 1E-33DL
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __REGISTER_PREFIX__ 
#define __USER_LABEL_PREFIX__ 
#define __GNUC_STDC_INLINE__ 1
#define __NO_INLINE__ 1
#define __CHAR_UNSIGNED__ 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZEOF_PTRDIFF_T__ 4
#define _ARCH_PPC 1
#define __vector __attribute__((altivec(vector__)))
#define __pixel __attribute__((altivec(pixel__))) unsigned short
#define __bool __attribute__((altivec(bool__))) unsigned
#define vector vector
#define pixel pixel
#define bool bool
#define _Bool _Bool
#define __builtin_vsx_xxland __builtin_vec_and
#define __builtin_vsx_xxlandc __builtin_vec_andc
#define __builtin_vsx_xxlnor __builtin_vec_nor
#define __builtin_vsx_xxlor __builtin_vec_or
#define __builtin_vsx_xxlxor __builtin_vec_xor
#define __builtin_vsx_xxsel __builtin_vec_sel
#define __builtin_vsx_vperm __builtin_vec_perm
#define __builtin_vsx_xvmaddadp __builtin_vsx_xvmadddp
#define __builtin_vsx_xvmaddmdp __builtin_vsx_xvmadddp
#define __builtin_vsx_xvmaddasp __builtin_vsx_xvmaddsp
#define __builtin_vsx_xvmaddmsp __builtin_vsx_xvmaddsp
#define __builtin_vsx_xvmsubadp __builtin_vsx_xvmsubdp
#define __builtin_vsx_xvmsubmdp __builtin_vsx_xvmsubdp
#define __builtin_vsx_xvmsubasp __builtin_vsx_xvmsubsp
#define __builtin_vsx_xvmsubmsp __builtin_vsx_xvmsubsp
#define __builtin_vsx_xvnmaddadp __builtin_vsx_xvnmadddp
#define __builtin_vsx_xvnmaddmdp __builtin_vsx_xvnmadddp
#define __builtin_vsx_xvnmaddasp __builtin_vsx_xvnmaddsp
#define __builtin_vsx_xvnmaddmsp __builtin_vsx_xvnmaddsp
#define __builtin_vsx_xvnmsubadp __builtin_vsx_xvnmsubdp
#define __builtin_vsx_xvnmsubmdp __builtin_vsx_xvnmsubdp
#define __builtin_vsx_xvnmsubasp __builtin_vsx_xvnmsubsp
#define __builtin_vsx_xvnmsubmsp __builtin_vsx_xvnmsubsp
#define __HAVE_BSWAP__ 1
#define __BIG_ENDIAN__ 1
#define _BIG_ENDIAN 1
#define _CALL_SYSV 1
#define __VEC_ELEMENT_REG_ORDER__ __ORDER_BIG_ENDIAN__
#define __PPC 1
#define __PPC__ 1
#define PPC 1
#define __powerpc 1
#define __powerpc__ 1
#define powerpc 1
#define __AMIGA 1
#define __AMIGA__ 1
#define AMIGA 1
#define __AMIGAOS 1
#define __AMIGAOS__ 1
#define AMIGAOS 1
#define __AMIGAOS4 1
#define __AMIGAOS4__ 1
#define AMIGAOS4 1
#define __amiga 1
#define __amiga__ 1
#define amiga 1
#define __amigaos 1
#define __amigaos__ 1
#define amigaos 1
#define __amigaos4 1
#define __amigaos4__ 1
#define amigaos4 1
#define __NEWLIB 1
#define __NEWLIB__ 1
#define NEWLIB 1
#define __ELF__ 1
# 1 "<command-line>"
# 1 "0.c"

**Comment by raziel-** [comment] 2018-10-09 18:51
0.3.14 with BE --> MIDI Broken --> WAV Broken
0.3.14 without BE --> MIDI Fine --> WAV Broken

0.4.2 with BE --> MIDI Fine --> WAV Fine
0.4.2 without BE --> MIDI Fine --> WAV Broken

I can see a pattern there

**Comment by sezero** [comment] 2018-10-09 18:55
> #define BYTE_ORDER ORDER_BIG_ENDIAN
> #define FLOAT_WORD_ORDER ORDER_BIG_ENDIAN
> [...]
> #define __BIG_ENDIAN__ 1
> #define _BIG_ENDIAN 1

You _are_ running on big endian. I don't yet see how the issue is happening.

> 0.3.14 with BE --> MIDI Broken --> WAV Broken
> 0.3.14 without BE --> MIDI Fine --> WAV Broken
> 
> 0.4.2 with BE --> MIDI Fine --> WAV Fine
> 0.4.2 without BE --> MIDI Fine --> WAV Broken

Thanks for the further info.

**Comment by sezero** [comment] 2018-10-09 21:18
I revived my amigaos4 cross-compiler toolchain and built 0.3.14 using gcc4.2:
see attached zip.  Does it work correctly for you?

[0314.zip](https://github.com/Mindwerks/wildmidi/files/2462243/0314.zip)

**Comment by raziel-** [comment] 2018-10-10 06:05
Yes, both MIDI replay and .wav creation is fine

**Comment by sezero** [comment] 2018-10-10 06:18
Then you have a broken toolchain??
Because I compiled 0.3.14 as is, without changing endian defines at all.

**Comment by raziel-** [comment] 2018-10-10 06:34
But it would be broken since 4.2.4 and i doubt that.

I'm also compiling other projects with the same and they are working fine.
Do you maybe have a hint where i could look?

**Comment by sezero** [comment] 2018-10-10 06:55
Unfortunately, no.  This is my toolchain:

- binutils-2.14-20080224, from here, without changes:
  https://sourceforge.net/p/adtools/code/HEAD/tree/releases/binutils-2.14-20080224/
- gcc-4.2.4-20080621, from here:
  https://sourceforge.net/p/adtools/code/HEAD/tree/releases/gcc-4.2.4-20080621/
  To this, I applied gcc-4_2-branch changes from gcc svn, and also the
  PR target/49008 patch from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49008
  I don't think that they matter for our case here.
- AmigaOS4x SDK 53.24, from here:
  http://www.hyperion-entertainment.biz/index.php/downloads?view=details&file=69

**Comment by sezero** [comment] 2018-10-10 07:35
One thing I can think of is that you have a some offending environment
variable messing up things. Other than that I don't know.

Should I close this as invalid?

**Comment by raziel-** [comment] 2018-10-10 07:45
The only envvars i'm using...

type ENVARC:CXXFLAGS
--std=gnu++11
type ENVARC:LDFLAGS 
-athread=native -Wl,--no-keep-memory -L/sdk/local/newlib/lib

I guess you can close it then :-/
I don't want to waste your time any longer, thank you for patience and sorry for the noise

**Closed** 2018-10-10 07:51 UTC
Labels: invalid

**Comment by sezero** [comment] 2018-10-10 10:10
I closed this for now.  But if @BSzili finds anything fishy about the code
or the build flags, I'll reopen.

**Comment by sezero** [comment] 2018-10-10 14:15
@raziel-: One last idea:  Take an unmodified wildmidi-0.3.14
(or take the wildmidi-0.3 branch from the git), and add -fsigned-char
to CFLAGS, like:
```
diff --git a/amiga/Makefile b/amiga/Makefile
index 1d1fe2c..908444b 100644
--- a/amiga/Makefile
+++ b/amiga/Makefile
@@ -23,6 +23,7 @@ endif
 
 INCLUDE = -I. -I../include
 CFLAGS = $(INCLUDE) -Wall -W -fno-common
+CFLAGS += -fsigned-char
 ARFLAGS = cr
 LD = $(CC)
 LDFLAGS = -L. -lWildMidi
```

Does it help?

**Comment by raziel-** [comment] 2018-10-10 14:35
gcc -c -I. -I../include -Wall -W -fno-common -fsigned-char -O2 -DWORDS_BIGENDIAN=1 -D__USE_INLINE__ -D__USE_OLD_TIMEVAL__

I'm afraid not, both MIDI and WAV produce noise with this switch in place

**Comment by sezero** [comment] 2018-10-10 14:43
Well it was worth a try.  Don't have any other ideas.
@BSzili couldn't find anything wrong with the code yet either.

**Comment by raziel-** [comment] 2018-10-10 15:32
@sezero

Still, your time and help are appreciated

Thank you

PS: I'm pretty sure there ARE differences between a cross and a native build, though i'm not the right one to look at what it is and why it doesn't work...maybe i bug the SDK devs about it.
